//! Embeds the application icon into the Windows executables.
//!
//! No-op everywhere else. The icon is generated by
//! `packaging/icon/make_icons.py` and committed, so a plain `cargo build` needs
//! no Python; if the file is missing the build still succeeds without an icon
//! rather than failing.

fn main() {
    #[cfg(windows)]
    {
        const ICON: &str = "packaging/icon/garld.ico";
        if std::path::Path::new(ICON).exists() {
            let mut resource = winresource::WindowsResource::new();
            resource.set_icon(ICON);
            resource.set("ProductName", "garld");
            resource.set("FileDescription", "GitHub Action Runner Local Dashboard");
            if let Err(error) = resource.compile() {
                println!("cargo:warning=could not embed the Windows icon: {error}");
            }
        } else {
            println!("cargo:warning={ICON} is missing; building without an icon");
        }
        println!("cargo:rerun-if-changed={ICON}");
    }
}
